// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jihhiptkravfjnzsuigc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImppaGhpcHRrcmF2ZmpuenN1aWdjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwODQ0NTcsImV4cCI6MjA2MjY2MDQ1N30.5p2Fl5NpUtW1D7lP82pU4zYKOXoSH_OFMI2xMpldIvU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);